apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: grafana
  namespace: gms-monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
