apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: gms-monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
    relabelings:
    - targetLabel: CI
      replacement: "CicK8sSplunk"
    - targetLabel: env
      replacement: "dev"
    - targetLabel: site
      replacement: "cic"
    - targetLabel: role
      replacement: "k8s"

  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
