apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-snow-webhook-config
  namespace: gms-monitoring
data:
  config.ini: |-
    [DEFAULT]
    snowurls=["{{ gms_monitoring.snowurls}}"]
    runbookurl="{{ gms_monitoring.runbookurl }}"
    k8s_CI="{{ platform.name }}"
    k8s_env=dev
    k8s_site=cic
    k8s_role=k8s
    k8s_instance_url="https://{{ platform.controller }}/bdswebui/k8s/cluster-dashboard?id=/api/v2/k8scluster/1"
