---
platform:
  name: RTLAB
  type: onprem
  controller: mip-bdcs-vm31.mip.storage.hpecorp.net
  api_scheme: http
  install:
    install_type: non-agent-based-install

ecp_credentials:
  # Default installation accounts
  site_admin_id: admin
  site_admin_password: admin123
  ssh:
#    access_type: ssh_key_access
    access_type: password_access
#    keypair_file: /home/stack/.ssh/prod_ecp_rsa
#    keypair_name: prod_ecp_rsa
#    key_passphrase: bubAIdT^k2l}
    password: admin123
    username: root
    usergroup: root

ecp_k8s:
  master_nodes:
    disks:
      ephemeral_disks:
        - /dev/sdb
        # - /dev/sdc
      persistent_disks:
        - /dev/sdc
    hosts:
      - mip-bdcs-vm33.mip.storage.hpecorp.net     # 16.143.22.158  K8s Master 1
    no_tenant_storage: false

  # ingress_nodes:
  #   disks:
  #     ephemeral_disks:
  #       - /dev/sdb
  #       - /dev/sdc
  #     persistent_disks:
  #       - /dev/sdc
  #   hosts:
  #     - hpecp-splunk.mip.storage.hpecorp.net      # 16.143.22.159  K8s Ingress 1
  #     - mip-bdcs-vm35.mip.storage.hpecorp.net     # 16.143.22.160  K8s Ingress 2
  #   no_tenant_storage: true

  # cp_nodes:
  #   disks:
  #     ephemeral_disks:
  #       - /dev/sdb
  #       - /dev/sdc
  #     persistent_disks:
  #       - /dev/sdc
  #   hosts:
  #     - hpecp-splunk-master.mip.storage.hpecorp.net   # 16.143.22.161  K8s CP Worker 1
  #     - mip-bdcs-vm37.mip.storage.hpecorp.net         # 16.143.22.162  K8s CP Worker 2
  #   no_tenant_storage: true

  worker_nodes:
    disks:
      ephemeral_disks:
        - /dev/sdb
        # - /dev/sdc
      persistent_disks:
        - /dev/sdc
    hosts:
      # - hpecp-splunk.mip.storage.hpecorp.net          # 16.143.22.159  K8s Ingress 1
      # - mip-bdcs-vm35.mip.storage.hpecorp.net         # 16.143.22.160  K8s Ingress 2
      # - hpecp-splunk-master.mip.storage.hpecorp.net   # 16.143.22.161  K8s CP Worker 1
      # - mip-bdcs-vm37.mip.storage.hpecorp.net         # 16.143.22.162  K8s CP Worker 2
      - mip-bdcs-vm38.mip.storage.hpecorp.net         # 16.143.22.163
      # - mip-bdcs-vm39.mip.storage.hpecorp.net         # 16.143.22.164
    no_tenant_storage: false

  ###############################################
  # ONLY USED TO DELETE K8S HOSTS FROM PLATFORM #
  # The list can be either IPs or FQDNs         #
  ###############################################
  hosts_to_delete:
    list:
      - mip-bdcs-vm35.mip.storage.hpecorp.net   
      - mip-bdcs-vm37.mip.storage.hpecorp.net    
      # - mip-bdcs-vm39.mip.storage.hpecorp.net
    # status: ready      
