---
#==================================================================================================================================
# Variables to override the playbook defaults and specify which tasks will run in the install_ecp_control_plane.yml playbook
# NOTE: By default, the following (5) tasks are run: install_controller, add_gateways, add_ha_hosts, configure_ha and add_host_tags
# You can override this behavior by uncommenting the appropriate line(s) to select which task(s) should not run
#==================================================================================================================================
#install_controller: no
#add_gateways: no
#add_ha_hosts: no
#configure_ha: no
#add_host_tags: no

#==================================================================================================================================
# These variables govern the execution of optional tasks. These tasks are not run by default in install_ecp_control_plane playbook
# You can override this behavior by uncommenting the appropriate line(s) to select which task(s) should run
#==================================================================================================================================
#configure_gateway_ports: yes
#configure_airgap: yes
#configure_notification: yes
# NOTE: these tasks are only needed with ECP 5.1
#apply_ecp_patches: yes
#apply_ntp_fix_primary: yes
#apply_ntp_fix_shadow: yes

platform:
  name: RTLAB
  type: onprem
  api_scheme: http    # Setting for API calls - usually http regardless
  controller: 
    config:
      bd_domain: hpelab
      bd_prefix: ecp
      int_start_ip: 172.20.0.2
      int_end_ip: 172.20.255.254
      int_gw_ip: 172.20.0.1
      int_nw_mask: 16
      # ssl_cert_file: /var/lib/awx/mip-bdcs-vm19.mip.storage.hpecorp.net/cert.pem
      # ssl_cert_key_file: /var/lib/awx/mip-bdcs-vm19.mip.storage.hpecorp.net/key.pem
    disks:      
      node_disks:
        - /dev/sdb
      hdfs_disks:
        - /dev/sdc
    no_tenant_storage: false
    host: mip-bdcs-vm31.mip.storage.hpecorp.net
  gateways:
    config:
      gateway_set_hostname: hpecp-lab-gw.mip.storage.hpecorp.net
      # ssl_cert_file: cert.pem
      # ssl_key_file: key.pem
      port_mapping_start: 10000
      port_mapping_end: 11000
    hosts:
      - hpecp-lab-gw.mip.storage.hpecorp.net    # Gateway 1
  install:
    install_type: non-agent-based-install
    install_as_root: true
    ###############################################
    # Installer and Prechecks file info for ECP 5.3
    ###############################################  
    bin_url: https://bluedata-qa-releases.s3.amazonaws.com/5.3.1-pre-release/hpe-cp-rhel-release-5.3-3033.bin
    installer_file: "hpe-cp-rhel-release-5.3-3033.bin"
    # bin_url: https://bluedata-qa-releases.s3.amazonaws.com/5.3.1-pre-release/hpe-cp-rhel-release-5.3-3032.bin
    # installer_file: "hpe-cp-rhel-release-5.3-3032.bin"
    #bin_url: "http://16.143.20.46:8080/rock/golden/5.3-GA/3031/hpe-cp-rhel-release-5.3-3031.bin"
    #installer_file: "hpe-cp-rhel-release-5.3-3031.bin"
    prechecks_file: "hpe-cp-rhel-prechecks-5.3.bin"
    #-----------------------------------------
    # Installer and Prechecks file for ECP 5.2  
    #-----------------------------------------
    # bin_url: "https://bluedata-releases.s3.amazonaws.com/5.2/hpe-cp-rhel-release-5.2-3020.bin"  
    # installer_file: "hpe-cp-rhel-release-5.2-3020.bin"
    # prechecks_file: "hpe-cp-rhel-prechecks-5.2.bin"
    #-----------------------------------------
    # Installer and Prechecks file for ECP 5.1  
    #-----------------------------------------
    # bin_url: "https://bluedata-releases.s3.amazonaws.com/5.1/hpe-cp-rhel-release-5.1-3011.bin"
    # installer_file: hpe-cp-rhel-release-5.1-3011
    # prechecks_file: "hpe-cp-rhel-prechecks-5.2.bin"
    no_tenant_isolation: false
  proxy: http://web-proxy.corp.hpecorp.net:8080 
  rest_protocol: http
  validate_certs: no
  tools_dir: "/root/tools"         # place to store the kits like kubectl

ecp_airgap:
  container_repo_url: 16.143.22.165:8080/hpecp
  # container_repo_username:
  # container_repo_password:
  # container_repo_secure_flag:
  # container_repo_cert:
  # yum_repo_gpg_key:
  # yum_rpm_gpg_key:
  # yum_repo_url: http://16.143.20.46:8080/scratch/qa/repos/kubernetes/   # Unsupported - bad RPM
  yum_repo_url: http://bd-repos1.mip.storage.hpecorp.net/kubernetes/
  
ecp_credentials:
  site_admin_id: admin 
  site_admin_password: admin123  # Used by epicctl to set the default password for the site admin account during installation
  ssh:
    # access_type: ssh_key_access
    access_type: password_access
    # keypair_file: /home/stack/.ssh/prod_ecp_rsa
    # keypair_name: prod_ecp_rsa
    # key_passphrase: bubAIdT^k2l}
    password: admin123
    username: root
    usergroup: root

ecp_epic:
  ha_nodes:
    disks:
      node_disks:
        - /dev/sdb
        # - /dev/sdc
      hdfs_disks:
        - /dev/sdc
    hosts:
      - mip-bdcs-vm33.mip.storage.hpecorp.net    # 16.143.22.158 Shadow
      - mip-bdcs-vm35.mip.storage.hpecorp.net    # 16.143.22.160 Arbiter
    no_tenant_storage: true
    shadow_host: mip-bdcs-vm33.mip.storage.hpecorp.net   # 16.143.22.158 Shadow
    arbiter_host: mip-bdcs-vm35.mip.storage.hpecorp.net  # 16.143.22.160 Arbiter
  ###############################################
  # ONLY USED TO DELETE EPIC HOSTS FROM PLATFORM #
  # The list can be either IPs or FQDNs         #
  ###############################################
  hosts_to_delete:
    list:
      - mip-bdcs-vm35.mip.storage.hpecorp.net   
      - mip-bdcs-vm37.mip.storage.hpecorp.net    
      # - mip-bdcs-vm39.mip.storage.hpecorp.net
    # status: ready      

# ecp_notification:
  # snmp:
      # server: "10.9.7.232"
      # community: "public"
      # engine: "Engine"
      # user: "Username"
      # authpassword: "Authpassword"
      # authprotocol: "MD5"          # SHA, MD5
      # privilege: "authPriv"        # authPriv, authNoPriv, noAuthNoPriv
      # privprotocol: "AES"          # AES, DES
      # privpassword: "privpassword"
  # smtp:
      # email: "test@mail.com"
      # server: "smtp@mail.com"
      # user: "username"
      # password: "password"

