apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: alertmanager-main
  namespace: gms-monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
