apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - pods
  verbs:
  - get
  - list
- nonResourceURLs:
  - /metrics
  verbs:
  - get
