apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: prometheus-k8s
  namespace: gms-monitoring
spec:
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
