apiVersion: v1
kind: Secret
metadata:
  name: mapr-user-secret
  namespace: mapr-nfscsi
type: Opaque
data:
  MAPR_CLUSTER_USER: "{{ mapr.cluster_user }}"
  MAPR_CLUSTER_PASSWORD: "{{ mapr.cluster_password }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mapr-ticket-secret
  namespace: mapr-nfscsi
type: Opaque
data:
  CONTAINER_TICKET: "{{ mapr.container_ticket }}"
