kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hostpath-pvc-1700g
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1700G
