kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-20g1
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5000G
