apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: tpp-venafi-issuer
  namespace: cert-manager
spec:
  venafi:
    zone: devops\cert-manager # Set this to the Venafi policy zone you want to use
    tpp:
      url: https://tpp.venafi.example/vedsdk # Change this to the URL of your TPP instance
      caBundle: <base64 encoded string of caBundle PEM file, or empty to use system root CAs>
      credentialsRef:
        name: tpp-secret