---
# Validate vars for HA hosts to add
- fail:
    msg: "Error: In order to configure EPIC Worker nodes, you must provide the disk configuration, hostname(s) and the no_tenant_storage flag information for the hosts"
  when: 
    (ecp_epic.worker_nodes is undefined) or
    (ecp_epic.worker_nodes.no_tenant_storage is undefined) or
    (ecp_epic.worker_nodes.hosts is undefined) or
    (ecp_epic.worker_nodes.hosts is defined and (ecp_epic.worker_nodes.hosts is not iterable or ecp_epic.worker_nodes.hosts|length < 1))  
      
- name: Create a fact with the list of EPIC Worker node hosts to be added    
  set_fact:
    hosts_to_add:  "{{ ecp_epic.worker_nodes.hosts }}"

- debug:
    msg: 
    - "*** Installing EPIC Workers for ECP ***"
    - "Input file content: "
    - "{{ lookup('template', '_add_epic_hosts.j2') }}"

- name: Prepare input file for epicctl.
  template:
    src: add_epic_hosts.j2
    dest: "/tmp/{{ platform.name }}_add_epic_hosts.yml"
    mode: 0777

- name: Get version of epicctl
  command: "epicctl -v"
  register: res_ver
  failed_when: res_ver.rc != 0

- name: Run epicctl command to install epic workers for HA
  command: "epicctl op -f /tmp/{{ platform.name }}_add_epic_hosts.yml -n {{ platform.name }}"
  register: res
  failed_when: res.rc != 0

# Set hcp_host_id variable values in Ansible inventory

- debug:
    msg: "{{ res.stdout }}"
