---
  - name: Create a fact with the session info from the API call  
    set_fact:
      input_file: "/tmp/{{platform.name }}_add_k8s_hosts.yml"
    
  # - name: Create a fact with the list of K8s hosts to be added using the ecp_k8s.hosts variable if it is defined   
  #   set_fact:
  #     hosts_to_add:  "{{ ecp_k8s.hosts }}"
  #   when: ecp_k8s.hosts is defined  

  - name: Create a fact with the list of K8s hosts to be installed using the host inventory group if the ecp_k8s.hosts list doesn't exist   
    set_fact:
      ecp_k8s: "{{ ecp_k8s | combine({ 'hosts': groups.k8s_hosts })}}"
    when: ecp_k8s.hosts is undefined  

  - debug:
      msg:
      - "*** Is ecp_k8s.hosts iterable? ***"
      - "{{ ecp_k8s.hosts is iterable }}"
      - "*** ecp_k8s.hosts length ***"
      - "{{ ecp_k8s.hosts | length }}"

  - name: Prepare input file for epicctl (skipping any in repair_pool)
    template:
      src: add_k8s_hosts.j2
      dest: "{{ input_file }}"
      mode: 0777
  
  - debug:
      msg:
      - "*** Adding K8s Hosts ***"
      - "*** Input file content: "
      - "{{ lookup('template', 'add_k8s_hosts.j2') | to_nice_yaml }}"

  - name: Setting up and configuring k8s hosts.
    shell: epicctl op -f {{ input_file }} -n {{ platform.name }} --defaultpassword "{{ credentials.site_admin_password }}"
    register: res
    failed_when: res.rc != 0

