---
- name: Prepare input file for epicctl.
  template:
    src: add_gateways.j2
    dest: "/tmp/{{ platform.name }}_platform_gateways.yml"
    mode: 0777

- debug:
    msg: 
    - "*** Installing Gateways for HPE CP Control Plane ***"
    - "Input file content: "
    - "{{ lookup('template', 'add_gateways.j2') }}"

- name: Run epicctl command to install gateways
  command: "epicctl op -f /tmp/{{ platform.name }}_platform_gateways.yml -n {{ platform.name }}"
  register: res
  failed_when: res.rc != 0

# Set hcp_host_id variable values in Ansible inventory

- debug:
    msg: "{{ res.stdout }}"
