---
- name: Create a fact with the session info from the API call  
  set_fact:
    input_file: "/tmp/{{platform.name }}_add_k8s_hosts.yml"

- name: Create a fact for the lists of K8s hosts to add  
  set_fact:
    hosts_to_add: "{{ hosts_to_add|default([]) }}"

# Validate vars for K8s computer master node hosts to add
- fail:
    msg: "Error: If you specify K8s compute cluster master nodes then the disk configuration, host names and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.master_nodes is defined and ecp_k8s.master_nodes.hosts is undefined) or
    (ecp_k8s.master_nodes.hosts is defined and (ecp_k8s.master_nodes.hosts is not iterable or ecp_k8s.master_nodes.hosts|length < 1)) or
    (ecp_k8s.master_nodes is defined and ecp_k8s.master_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.master_nodes is defined and ecp_k8s.master_nodes.disks.ephemeral_disks is defined and (ecp_k8s.master_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.master_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.master_nodes is defined and ecp_k8s.master_nodes.no_tenant_storage is undefined)
      
- name: Create a fact with the list of K8s master node hosts to be added    
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.master_nodes.hosts }}"
  when: ecp_k8s.master_nodes.hosts is defined and ecp_k8s.master_nodes.hosts is iterable 

# Validate vars for K8s computer worker node hosts to add
- fail:
    msg: "Error: If you specify K8s compute cluster worker nodes then the disk configuration, host names and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.worker_nodes is defined and ecp_k8s.worker_nodes.hosts is undefined) or
    (ecp_k8s.worker_nodes.hosts is defined and (ecp_k8s.worker_nodes.hosts is not iterable or ecp_k8s.worker_nodes.hosts|length < 1)) or
    (ecp_k8s.worker_nodes is defined and ecp_k8s.worker_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.worker_nodes is defined and ecp_k8s.worker_nodes.disks.ephemeral_disks is defined and (ecp_k8s.worker_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.worker_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.worker_nodes is defined and ecp_k8s.worker_nodes.no_tenant_storage is undefined)
      
- name: If there are master nodes specified, add the list of K8s compute worker node hosts to the list   
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.worker_nodes.hosts }}"
  when: 
    - ecp_k8s.worker_nodes.hosts is defined and ecp_k8s.worker_nodes.hosts is iterable 
  
# Validate vars for K8s Ingress nodes hosts to add
- fail:
    msg: "Error: If you specify K8s compute cluster ingress nodes, then the disk configuration, hosts and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.ingress_nodes is defined and ecp_k8s.ingress_nodes.hosts is undefined) or
    (ecp_k8s.ingress_nodes.hosts is defined and (ecp_k8s.ingress_nodes.hosts is not iterable or ecp_k8s.ingress_nodes.hosts|length < 1)) or
    (ecp_k8s.ingress_nodes is defined and ecp_k8s.ingress_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.ingress_nodes is defined and ecp_k8s.ingress_nodes.disks.ephemeral_disks is defined and (ecp_k8s.ingress_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.ingress_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.ingress_nodes is defined and ecp_k8s.ingress_nodes.no_tenant_storage is undefined)

- name: Create a fact with the list of K8s Ingress node hosts to be added    
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.ingress_nodes.hosts }}"
  when:
    - ecp_k8s.ingress_nodes.hosts is defined and ecp_k8s.ingress_nodes.hosts is iterable

# Validate vars for K8s CP Worker nodes hosts to add
- fail:
    msg: "Error: If you specify K8s compute cluster CP Worker nodes, then the disk configuration, hosts and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.cp_nodes is defined and ecp_k8s.cp_nodes.hosts is undefined) or
    (ecp_k8s.cp_nodes.hosts is defined and (ecp_k8s.cp_nodes.hosts is not iterable or ecp_k8s.cp_nodes.hosts|length < 1)) or
    (ecp_k8s.cp_nodes is defined and ecp_k8s.cp_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.cp_nodes is defined and ecp_k8s.cp_nodes.disks.ephemeral_disks is defined and (ecp_k8s.cp_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.cp_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.cp_nodes is defined and ecp_k8s.cp_nodes.no_tenant_storage is undefined)
      
- name: Create a fact with the list of K8s CP Worker node hosts to be added    
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.cp_nodes.hosts }}"
  when:
    - ecp_k8s.cp_nodes.hosts is defined and ecp_k8s.cp_nodes.hosts is iterable

# Validate vars for K8s data fabric master node hosts to add
- fail:
    msg: "Error: If you specify K8s data fabric master nodes then the disk configuration, host names and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.hosts is undefined) or
    (ecp_k8s.df_master_nodes.hosts is defined and (ecp_k8s.df_master_nodes.hosts is not iterable or ecp_k8s.df_master_nodes.hosts|length < 1)) or
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.disks.ephemeral_disks is defined and (ecp_k8s.df_master_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.df_master_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.disks.persistent_disks is undefined) or
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.disks.persistent_disks is defined and (ecp_k8s.df_master_nodes.disks.persistent_disks is not iterable or ecp_k8s.df_master_nodes.disks.persistent_disks|length < 1)) or
    (ecp_k8s.df_master_nodes is defined and ecp_k8s.df_master_nodes.no_tenant_storage is undefined)
      
- name: Add the K8s data fabric master node hosts to the list to be added    
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.df_master_nodes.hosts }}"
  when: ecp_k8s.df_master_nodes.hosts is defined and ecp_k8s.df_master_nodes.hosts is iterable 

# Validate vars for K8s data fabric worker node hosts to add
- fail:
    msg: "Error: If you specify K8s data fabric worker nodes then the disk configuration, host names and tenant_storage flag must be provided"
  when: 
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.hosts is undefined) or
    (ecp_k8s.df_worker_nodes.hosts is defined and (ecp_k8s.df_master_nodes.hosts is not iterable or ecp_k8s.df_worker_nodes.hosts|length < 1)) or
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.disks.ephemeral_disks is undefined) or
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.disks.ephemeral_disks is defined and (ecp_k8s.df_worker_nodes.disks.ephemeral_disks is not iterable or ecp_k8s.df_worker_nodes.disks.ephemeral_disks|length < 1)) or
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.disks.persistent_disks is undefined) or
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.disks.persistent_disks is defined and (ecp_k8s.df_worker_nodes.disks.persistent_disks is not iterable or ecp_k8s.df_worker_nodes.disks.persistent_disks|length < 1)) or
    (ecp_k8s.df_worker_nodes is defined and ecp_k8s.df_worker_nodes.no_tenant_storage is undefined)
      
- name: Create a fact with the list of K8s data fabric worker node hosts to be added    
  set_fact:
    hosts_to_add:  "{{ hosts_to_add + ecp_k8s.df_worker_nodes.hosts }}"
  when: ecp_k8s.df_worker_nodes.hosts is defined and ecp_k8s.df_worker_nodes.hosts is iterable 

- debug:
    msg:
    - "*** Preparing to add K8s Hosts to ECP ***"
    - "Hosts being added:"
    - "{{ hosts_to_add }}"

- name: Prepare input file for epicctl (skipping any in repair_pool)
  template:
    src: add_k8s_hosts.j2
    dest: "{{ input_file }}"
    mode: 0777
  
- debug:
    msg:
    - "*** Adding K8s Hosts ***"
    - "*** Input file content: "
    - "{{ lookup('template', 'add_k8s_hosts.j2') | to_nice_yaml }}"

- name: Setting up and configuring k8s hosts.
  shell: "epicctl op -f {{ input_file }} -n {{ platform.name }} --defaultpassword {{ ecp_credentials.site_admin_password }}"
  register: res
  failed_when: res.rc != 0
