---
- name: Prepare input file for epicctl.
  template:
    src: k8shosts.j2
    dest: "/tmp/{{ common.name }}_k8shosts.yml"
    mode: 0777
  
- name: Run epicctl command to add K8s hosts
  command: "epicctl op -f /tmp/{{ common.name }}_k8shosts.yml -n {{ common.name }} "
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- K8s hosts result: {{ res.stdout }}"
