---
- name: Prepare input file for epicctl.
  template:
    src: add_ha_workers.j2
    dest: "/tmp/{{ platform.name }}_platform_ha_workers.yml"
    mode: 0777

- debug:
    msg: 
    - "*** Installing HA Workers for HPE CP Control Plane ***"
    - "Input file content: "
    - "{{ lookup('template', 'add_ha_workers.j2') }}"

- name: Get version of epicctl
  command: "epicctl -v"
  register: res_ver
  failed_when: res_ver.rc != 0

- name: Run epicctl command to install epic workers for HA
  command: "epicctl op -f /tmp/{{ platform.name }}_platform_ha_workers.yml -n {{ platform.name }}"
  register: res
  failed_when: res.rc != 0

# Set hcp_host_id variable values in Ansible inventory

- debug:
    msg: "{{ res.stdout }}"
