---
- name: Obtain session token
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Prepare input file for epicctl.
  template:
    src: k8shosts.j2
    dest: "/tmp/{{ common.name }}_k8shosts.yml"
    mode: 0777
  
- name: Run epicctl command to setup and configure K8h worker nodes
  command: "epicctl op -f /tmp/{{ common.name }}_k8shosts.yml -n {{ common.name }}"
  register: res
  failed_when: res.rc != 0
  #failed_when: false

#- name: add k8shost list for setting ephemeral disk
#  uri:
#    url: http://{{ groups.primary_controller[0] }}:8080/v2/worker/k8shost
#    return_content: yes
#    method: GET
#    body_format: json
#    status_code: 201
#  register: k8shost_data
  
- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
    method: DELETE
    status_code: 204
  register: delsession_res

- debug:
    msg: Session: {{ session_res.location  | urlsplit('path') }} -- K8s hosts result: {{ res.stdout }}
