---
# This task addresses a bug in ECP 5.1-3011 where the installer fails to open UDP port 123 in iptables
# In addition, it pushed in a copy of /etc/chrony.conf from the primary controller obtained in an earlier task
# and updates the peer setting to point to the primary

- name: Edit ip_tables.json to replace tcp with udp for port 123
  replace:
    path: /etc/bluedata/iptables/bd_iptables.json
    backup: yes
    after: "\"ports\": 123,"
    before: "\"ports\": 5666,"
    regexp: "\"protocol\": \"tcp\""
    replace: "\"protocol\": \"udp\""

- name: Activate the updated iptables rules
  command: /usr/lib/python2.7/site-packages/bluedata/ovs/bds-ovs-config.py createfwrules

- name: Push in copy of /etc/chrony.conf from primary
  copy:
    backup: yes
    src:  /tmp/chrony.conf.primary/{{ platform.controller }}/etc/chrony.conf
    dest: /etc/chrony.conf

- name: Edit /etc/chrony.conf to replace peer with IP of primary controller
  replace:
    path: /etc/chrony.conf
    backup: yes
    regexp: "peer {{ hostvars[inventory_hostname]['ansible_host'] | regex_escape() }} iburst"
    replace: "peer {{ hostvars[platform.controller]['ansible_host'] }} iburst"

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted