---
- name: Ensure previous files and directories are clean before copy.
  command: rm -f /opt/bluedata/repositories/*
  register: res
  failed_when: res.rc != 0

- name: Ensure previous docker is removed.
  command: yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine -y
  register: res
  failed_when: res.rc != 0

- name: Ensure ports are free before installing controller.
  command: "{{ item }}"
  register: res
  failed_when: false
  with_items:
  - "pkill -9 httpd"
  - "pkill -9 haproxy"
  - "pkill -9 beam.smp"

#
# Dangerous command, be careful before cleanup
- name: Ensure storage disks are available.
  command:  "{{ item }}"
  register: res
  failed_when: false
  with_items:
  - "parted -ms /dev/sdb -- rm 1"
  - "wipefs -a /dev/sdb /dev/sdc"
  - "blockdev --rereadpt --flushbufs /dev/sdb /dev/sdc"
