---
- name: Obtain session token
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res
 
- name: Prepare configure air gap input file for epicctl.
  template:
    src: configure_airgap.j2
    dest: "/tmp/{{ common.name }}_configure_airgap.json"
    mode: 0777
 
- name: Configure platform for air gap
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/config/k8s
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: PUT
    body_format: json
    body: "{{ lookup('file','/tmp/CICL_configure_airgap.json') }}"
    status_code: 204
  register: airgap_res
  #failed_when: res.status != 200   

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
    method: DELETE
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- Airgap Configuration Result: {{ airgap_res.status }}"
     
