---
- name: Obtain session token
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/login"
    return_content: yes
    method: POST
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res
 
#- name: Prepare configure air gap input file for epicctl.
#  template:
#    src: configure_airgap.j2
#    dest: "/tmp/{{ platform.name }}_configure_airgap.json"
#    mode: 0777
 
- name: Configure platform for air gap
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v2/config/k8s"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: PUT
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
#    body: "{{ lookup('file','/tmp/CICL_configure_airgap.json') }}"
    body: "{{ lookup('template','configure_airgap.j2') }}"
    status_code: 204
  register: airgap_res

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- Airgap Configuration Result: {{ airgap_res.status }}"
