---
# This playbook creates a K8s Tenant by making a REST API call.
# It uses platform, credentials and k8s_tenant variables  

- name: Obtain session token
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/login"
    return_content: yes
    method: POST
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: { "name": "{{ ecp_credentials.site_admin_id }}", "password": "{{ ecp_credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Create a fact with the session info from the API call  
  set_fact:
    session_id: "{{ session_res.location  | urlsplit('path') }}"
   
# Get the current list of K8s clusters 
- name: Get the current set of K8s clusters 
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v2/k8scluster"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "application/json"
    method: GET
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 200
  register: k8scluster_res

- name: Create a fact with the list of K8s cluster from the API call  
  set_fact:
    k8scluster_list: "{{ k8scluster_res.json }}"
    cacheable: True

# Parse the k8s cluster name and ID from the JSON result of the GET k8scluster call and set target cluster ID
- name: Parse the K8s cluster name and ID from the JSON result of the GET k8scluster call
  set_fact:
    # set the id of the K8s cluster to associate with the new tenant if it matches the name of the supplied cluster
    tenant_k8s_cluster_id: "{{ item | json_query('cluster_id') }}"
    cacheable: true
  loop: "{{ k8scluster_list | json_query('_embedded.k8sclusters[*].{cluster_name: label.name, cluster_id: _links.self.href}') }}"
  when: item | json_query('cluster_name') == ecp_k8s.tenant.cluster_name  

- name: Create a fact with the JSON required for the REST API call  
  set_fact:
    tenant_JSON: "{{ lookup('template','create_k8s_tenant.j2') | from_yaml }}"
    cacheable: True

- debug:
    msg:
    - "*** Creating K8s Tenant ***"
    - "Input file Content: "
    - "{{ tenant_JSON | to_nice_yaml }}"

- name: Create K8s tenant
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/tenant"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: POST
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: "{{ tenant_JSON }}"
    status_code: 201
  register: tenant_res

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}"  
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- Create K8s Tenant Result: {{ tenant_res.status }}"
