---
- name: Obtain session token
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Create a fact with the session info from the API call  
  set_fact:
    session_id: "{{ session_res.location  | urlsplit('path') }}"
   
# Get the current list of tenants
- name: Get the current set of tenants 
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/tenant
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "application/json"
    method: GET
    status_code: 200
  register: tenant_res

- name: Create a fact with parsed list of tenants from the APPI call  
  set_fact:
    tenants_list: "{{ tenant_res.json | json_query('_embedded.tenants[*].{tenant_id: tenant_id, tenant_name: tenant_name, tenant_description: tenant_description, status: status}') }}"
    cacheable: True  

# Parse the k8s cluster name and ID from the JSON result of the GET k8scluster call and set target cluster ID
- name: Parse the K8s cluster name and ID from the JSON result of the GET k8scluster call
  set_fact:
    # set the id of the tenant to delete if it matches the name of the supplied tenant
    target_tenant_id: "{{ item | json_query('tenant_id') }}"
    cacheable: true
  when: "{{ item | json_query('tenant_name') == target_tenant_name }}"  
  loop: "{{ tenants_list | json_query('_embedded.tenants[*].{tenant_name: tenant_name, tenant_id: tenant_id}') }}"

- name: Delete K8s tenant
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/tenant
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: DELETE
    body_format: json
    body: ""
    status_code: 204
  register: tenant_delete_res

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}"  
    method: DELETE
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_id }} -- Delete Tenant Result: {{ tenant_delete_res.status }}"
