---
- name: Obtain session token
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/login"
    return_content: yes
    method: POST
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: { "name": "{{ ecp_credentials.site_admin_id }}", "password": "{{ ecp_credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Create a fact with the session info from the API call  
  set_fact:
    session_id: "{{ session_res.location  | urlsplit('path') }}"

# Get the current list of K8s tenants 
- name: Get the current set of K8s tenants 
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v2/tenant"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "application/json"
    method: GET
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 200
  register: tenant_res

- name: Create a fact with the list of tenants from the API call  
  set_fact:
    tenants_list: "{{ tenant_res.json }}"
    cacheable: True

# Parse the k8s tenant name and ID from the JSON result of the GET tenants call and set target tenant ID
- name: Parse the K8s cluster name and ID from the JSON result of the GET k8scluster call
  set_fact:
    # set the id of the tenant to delete if it matches the name of the supplied tenant
    target_tenant_id: "{{ item | json_query('tenant_id') | regex_replace('/api/v2/tenant/') }}"
    #target_tenant_id: "{{ item | json_query('tenant_id') }}"
    cacheable: true
  when: "{{ item | json_query('tenant_name') == ecp_k8s.tenant.target_tenant_name }}"  
  loop: "{{ tenants_list | json_query('_embedded.tenants[*].{tenant_name: label.name, tenant_id: _links.self.href}') }}"

- debug:
    msg: "ID of Tenant to be deleted: {{ target_tenant_id }}" 
      
- name: Delete K8s tenant
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/tenant/{{ target_tenant_id }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: ""
    status_code: 204
  register: tenant_delete_res

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}"  
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_id }} -- Delete Tenant Result: {{ tenant_delete_res.status }}"
