---
- name: Obtain session token
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Create a fact with the session info from the API call  
  set_fact:
    session_id: "{{ session_res.location  | urlsplit('path') }}"
    cacheable: True  

# Get the current list of K8s clusters 
- name: Get the current set of K8s clusters 
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/k8scluster
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "application/json"
    method: GET
    status_code: 200
  register: k8scluster_res

# Parse the k8s cluster name and ID from the JSON result of the GET k8scluster call and set target cluster ID
- name: Parse the K8s cluster name an ID from the JSON result of the GET k8scluster call
  set_fact:
    # set the id of the cluster to delete if it matches the name of the supplied cluster
    target_cluster_id: "{{ item | json_query('cluster_id') }}"
  when: "{{ item | json_query('cluster_name') == target_cluster_name }}"  
  loop: "{{ k8scluster_res.json | json_query('_embedded.k8sclusters[*].{cluster_name: label.name, cluster_id: _links.self.href}') }}"
  register: cluster_list

- debug: 
    msg: "Cluster to be deleted: {{ target_cluster_id }} Name: {{ target_cluster_name }}"
 
- name: Delete K8s Cluster
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080{{ target_cluster_id }}
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "*/*"
    method: DELETE
    status_code: 204
  register: del_cluster_res

#- name: Poll the status of cluster delete by making get call to /api/v2/k8scluster/k8scluster_id
#  command: epicctl api get -u "{{ k8scluster_uri }}" -n "OnPremSetup" -p {{ common.platform }} -o /tmp/get-response.json
#    vars:
#      getResp: "{{ (lookup('file', '/tmp/get-response.json') | from_json)['status'] }}"
#  register : res
#  failed_when: false # when resource is deleted, last get call returns 404, don't want to fail it
#  changed_when: false
#  retries: 30
#  delay: 10
#  until:  '"deleting" != getResp'

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}"  
    method: DELETE
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- Delete K8s Cluster Result: {{ del_cluster_res.status }}"

