---
#
# This playbook deletes k8s hosts from the platform
# It uses platform and ecp_credentials variables 

# Validate vars for nodes to delete
- fail:
    msg: "Error: Specify either a list of hosts to delete OR a status to use but not both"
  when: 
    - ecp_epic.hosts_to_delete.list is defined  
    - ecp_epic.hosts_to_delete.status is defined

- fail:
    msg: "Error: You must provide either a list of EPIC hosts to delete or a host status that will be used to delete all EPIC hosts in that status"
  when: 
    - (ecp_epic.hosts_to_delete.list is undefined or ecp_epic.hosts_to_delete.list is not iterable)
    - (ecp_epic.hosts_to_delete.status is undefined)

- name: Obtain session token
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/login"
    return_content: yes
    method: POST
    validate_certs: "{{ platform.validate_certs }}"
    body_format: json
    body: { "name": "{{ ecp_credentials.site_admin_id }}", "password": "{{ ecp_credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Create a fact with the session info from the API call  
  set_fact:
    session_id: "{{ session_res.location  | urlsplit('path') }}"
    cacheable: True  

# Get the current set of EPIC worker hosts 
- name: Get the current set of EPIC worker hosts 
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080/api/v1/workers"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
      accept: "application/json"
    method: GET
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 200
  register: epic_hosts_res

- name: Create a fact with the list of the current set of EPIC hosts  
  set_fact:
    epic_hosts_list: "{{ epic_hosts_res.json | json_query('_embedded.workers[*].{ansible_host: ip, host_id: _links.self.href, hostname: hostname, state: state, purpose: purpose, tags: tags}') }}"

# At this point, epic_hosts_list contains all the EPIC hosts in the platform
# now create the list of host ids to delete and the list of host IPs to restore if the operation needs to be rolled back
- name: Create empty list
  set_fact:
    epic_ids_to_delete: []
    epic_ips_to_restore: []
    cacheable: True

- name: Create list of hosts to delete based on enumerated list of EPIC hosts
  set_fact:
    epic_ids_to_delete: "{{ epic_ids_to_delete + [item | json_query('host_id')] }}"
    epic_ips_to_restore: "{{ epic_ips_to_restore + [item | json_query('hostname')] }}"
    cacheable: True
  when: 
    - ecp_epic.hosts_to_delete.list is defined
    - ecp_epic.hosts_to_delete is iterable
    - (item | json_query('ansible_host') in ecp_epic.hosts_to_delete.list or item | json_query('hostname') in ecp_epic.hosts_to_delete.list)
  loop: "{{ epic_hosts_list }}"

- name: Create list of hosts to delete based on EPIC host status
  set_fact:
    epic_ids_to_delete: "{{ epic_ids_to_delete + [item | json_query('host_id')] }}"
    epic_ips_to_restore: "{{ epic_ips_to_restore + [item | json_query('hostname')] }}"
    cacheable: True
  when:
    - ecp_epic.hosts_to_delete.status is defined
    - item | json_query('status') == ecp_epic.hosts_to_delete.status
  loop: "{{ epic_hosts_list }}"

# Use add_epic_hosts.j2 to create a YAML file for re-adding the hosts that were just deleted if the operation needs to be rolled back
- name: Create a fact with the session info from the API call  
  set_fact:
#    epic_hosts_list: "{{ epic_ips_to_restore }}"    # Override variable add_k8s_hosts.j2 will be looking for
    input_file: "/tmp/{{ platform.name }}_re-add_deleted_epic_hosts.yml"
    cacheable: True

- name: Prepare input file for API REST call in case we need to recover and put the hosts back in the platform
  template:
    src: re-add_epic_hosts.j2
    dest: "{{ input_file }}"
    mode: 0777

- debug:
    msg:
    - "*** Deleting EPIC Hosts ***"
    - "*** List of EPIC hosts to delete: "
    - "{{ epic_ids_to_delete }}"

- name: Delete EPIC hosts from platform
  uri:
    url: "{{ platform.rest_protocol }}://{{ platform.controller }}:8080{{ item }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}"
      Content-Type: "application/json"
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 204
  register: cluster_res
  loop: "{{ epic_ids_to_delete }}"

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_id }}" 
    method: DELETE
    validate_certs: "{{ platform.validate_certs }}"
    status_code: 204
  register: session_res
