---
- name: Obtain session token
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

# Get the current list of K8s clusters 
- name: Get the current set of K8s clusters 
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/worker/k8scluster
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}" 
      accept: "application/json"
    method: GET
    status_code: 200
  register: cluster_res

# Parse the k8s cluster name and ID from the JSON result of the GET k8scluster call and set target cluster ID
- name: Parse the k8s Host ID and IP address
  set_fact:
    # set the id of the cluster to delete if it matches the name of the supplied cluster
    target_cluster_id: "{{ item | json_query('cluster_id') }}"
  when: "{{ item | json_query('cluster_name') == target_cluster_name }}"  
  loop: "{{ k8shost_res.json | json_query('_embedded.k8shosts[*].{cluster_name: label.name, cluster_id: _links.self.href}') }}"
  register: cluster_list

- debug: 
    msg: "Cluster to be deleted: {{ target_cluster_id }} Name: {{ target_cluster_name }}"
 
- name: Delete K8s Cluster
  uri:
    url: http://{{ groups.primary_controller[0] }}:8080/api/v2/k8scluster
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}" 
      accept: "*/*"
      Content-Type: "application/json"
    method: DELETE
    status_code: 202
  register: del_cluster_res

- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
    method: DELETE
    status_code: 204
  register: delsession_res

- debug:
    msg: "Session: {{ session_res.location  | urlsplit('path') }} -- Delete K8s Cluster Result: {{ del_cluster_res.status }}"

