---
- name: Obtain session token
  uri:
    url: http://{{ primary_controller }}:8080/api/v1/login
    return_content: yes
    method: POST
    body_format: json
    body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
    status_code: 201
  register: session_res

- name: Get Kubeconfig for current user
  uri:
    url: http://{{ primary_controller }}:8080/api/v2/k8skubeconfig
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
      accept: "text/yaml"
    method: GET
    dest: /tmp/kubeconfig_{{ k8s.cluster.name }}.conf
    status_code: 200
    
  register: kubeconfig_res
    
#- name: Authenticate k8s cluster user
#  command: kubectl hpecp authenticate
#  register: res
#  failed_when: res.rc != 0


- name: label istio ingress nodes
  command: kubectl  --kubeconfig=/tmp/kubeconfig_{{ k8s.cluster.name }}.conf --context {{common.name}}-{{ k8s.cluster.name }}-{{credentials.site_admin_id}} label nodes {{ item }} istio-ingressgateway=true
  loop: "{{ groups['k8s_ingress_nodes'] }}"
  register: res
  failed_when: res.rc != 0

- name: Install Istio
  command: "/var/lib/awx/istio-1.6.5/bin/istioctl --kubeconfig=/tmp/kubeconfig_{{ k8s.cluster.name }}.conf --context {{common.name}}-{{ k8s.cluster.name }}-{{credentials.site_admin_id}} install --skip-confirmation"
  register: res
  failed_when: res.rc != 0
  
#- name: Install istio addon manifest
#  command: "{{ k8s.istio.istio_home}}/bin/istioctl  --kubeconfig=/tmp/kubeconfig_{{ k8s.cluster.name }}.conf --context {{common.name}}-{{ k8s.cluster.name }}-{{credentials.site_admin_id}} install -f {{ istio_manifest_file }} --skip-confirmation"
#  register: res
#  failed_when: res.rc != 0

- name: label splunk namespace
  command: kubectl  --kubeconfig=/tmp/kubeconfig_{{ k8s.cluster.name }}.conf  --context {{common.name}}-{{ k8s.cluster.name }}-{{credentials.site_admin_id}} label namespace {{ k8s.cluster.name }} istio-injection=enabled
  register: res
  failed_when: res.rc != 0
  
- name: Log out of session
  uri:
    url: "{{ session_res.location }}"
    return_content: yes
    headers:
      X-BDS-SESSION: "{{ session_res.location  | urlsplit('path') }}"  
    method: DELETE
    status_code: 204
  register: delsession_res
  
- debug:
    msg: "End Istio Install Session: {{ session_res.location  | urlsplit('path') }}"
