---
- name: Prepare input file for epicctl.
  template:
    src: platform_controller.j2
    dest: "/tmp/{{ platform.name }}_platform_controller.yml"
    mode: 0777

- debug:
    msg: 
    - "*** Installing HPE CP Control Plane (controller only) ***"
    - "Input file content: "
    - "{{ lookup('template', 'platform_controller.j2') }}"

- name: Run epicctl command to output its version
  command: "epicctl -v"
  register: res
  failed_when: res.rc != 0

- name: Run epicctl command to install ECP controller 
  command: "epicctl op -f /tmp/{{ platform.name }}_platform_controller.yml -n {{ platform.name }}"
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "{{ res.stdout }}"
