---
- name: Prepare input file for epicctl.
  template:
    src: platform.j2
    dest: "/tmp/{{ common.name }}_platform.yml"
    mode: 0777
  
- name: Run epicctl command to install controller, gateways and two EPIC workers (for shadow and arbiter)
  command: "epicctl op -f /tmp/{{ common.name }}_platform.yml -n {{ common.name }}"
  register: res
  failed_when: res.rc != 0

# Set hcp_host_id variable values in Ansible inventory

- debug:
    msg: "{{ res.stdout }}"
