---
# This playbook installs the ECP Primary Controller
- fail:
    msg: "Error: In order to install ECP, you must specify the host to use as well as the disk configuration, installation parameters and controller configuration information "
  when: 
    (platform.controller.config is undefined) or
    (platform.controller.host is undefined) or
    (platform.controller.disks is undefined) or
    (platform.install is undefined)  

- debug:
    msg: 
    - "*** Installing ECP Controller ***"
    - "Controller Host: {{ platform.controller.host }}"

- name: Prepare input file for epicctl.
  template:
    src: install_platform_controller.j2
    dest: "/tmp/{{ platform.name }}_install_platform_controller.yml"
    mode: 0777

- debug:
    msg: 
    - "*** Installing ECP Controller ***"
    - "Input file content: "
    - "{{ lookup('template', 'install_platform_controller.j2') }}"

- name: Run epicctl command to output its version
  command: "epicctl -v"
  register: res
  failed_when: res.rc != 0

- name: Run epicctl command to install ECP controller 
  command: "epicctl op -f /tmp/{{ platform.name }}_install_platform_controller.yml -n {{ platform.name }}"
  register: res
  failed_when: res.rc != 0

- debug:
    msg: "{{ res.stdout }}"
