---
- name: Prepare input file for epicctl.
  template:
    src: platform.j2
    dest: "/tmp/{{ common.name }}_platform.yml"
    mode: 0777
  
- name: Run epicctl command to setup and configure controller node
  command: "epicctl op -f /tmp/{{ common.name }}_platform.yml -n {{ common.name }}"
  register: res
  failed_when: res.rc != 0
  #failed_when: false

# Set hcp_host_id variable values in Ansible inventory

- debug:
    msg: "{{ res.stdout }}"
