---
# Parse the k8s Host ID, IP address, hostname and status from the JSON result of the GET k8shost call and set the hcp_host_id variable for each host
- name: Parse the k8s IP, Host ID, hostname and status into a record
  set_fact:
    hcp_host_id: "{{ item | json_query('host_id') | regex_replace('/api/v2/worker/k8shost/') }}"
    status: "{{ item | json_query('status') }}"
    is_ready:  "{{ item | json_query('status') == 'ready' }}"
    host: "{{ item | json_query('ansible_host') }}"
    test: test
    cacheable: true    
  delegate_facts: True
  delegate_to: "{{ item | json_query('ansible_host') }}"

- debug: 
    # msg: "Test: {{ test }} Worker Node IP: {{ hostvars[item].ansible_host }} Host ID: {{ hostvars[item].hcp_host_id }} Status: {{ hostvars[item].status }} Ready: {{ hostvars[item].is_ready }}"
    msg: "Test: {{ test }} "
