---
# This task uninstalls ECP components on the designated hosts by running the installer with the --erase --force options on each host and then removing the installer.
# This task assumes that the ECP installation was a non-agent based installation.
# It uses only one platform variable - platform.install.version as it mostly concerned with file manipulation and does not interact with ECP directly  
# NOTE: Prior to running this playbook, the installer bin file needs to be placed in the /tmp/ecp folder on the Tower server. 

- name: Find the location(s) of any matching ECP precheck bin files if they exist
  ansible.builtin.find:
    paths: /
    recurse: yes
    patterns: "{{ platform.install.installer_file }}"
    use_regex: yes
  register: result

- name: Report the number of matching installer files found on the host
  debug:
    msg: "There were {{ result.matched }} instances of the installer file found."
    
- name: Report the path of the first installer file instance found on the host
  debug:
    msg: " The path to the first instance of the installer file is: {{ result.files[0].path }}"
  when: 
    - result.files[0] is defined
    - result.matched >= 0

- name: Report the result of the find
  debug:
    msg: "The file data is: {{ result.files[0] }}"
  when: 
    - result.files[0] is defined
    - result.matched >= 0

- name: Create a fact for the path of the installer file if one exists on the host 
  set_fact:
    file_path: "{{ result.files[0].path }}"
    cacheable: True
  when:  
    - result.files[0] is defined
    - result.matched >= 0

- name: Set file stats for the installer file
  stat:
    path: "{{ file_path }}"
  register: file_data
  when:  
    - result.files[0] is defined
    - result.matched >= 0

- name: Report if the bin file exists and is executable
  debug:
    msg: "The file {{ file_path }} exists and is executable. Preparing to uninstall ECP..."
  when: 
    - result.files[0] is defined
    - result.matched >= 0
    - file_data.stat.exists
    - file_data.stat.executable  

- name: Report if the bin file exists and is NOT executable
  debug:
    msg: "The file {{ file_path }} exists but is NOT executable. Changing installer file to executable and preparing to uninstall ECP..."
  when: 
    - result.files[0] is defined
    - result.matched >= 0
    - file_data.stat.exists
    - not file_data.stat.executable  

- name: Make the installer bin executable if it exists and iasn't executable
  file:
    path: "{{ file_path }}"
    mode: a+x
  when: 
    - result.files[0] is defined
    - result.matched >= 0
    - file_data.stat.exists
    - not file_data.stat.executable

- name: Report if the bin file does NOT exist
  debug:
    msg: "No installer file exists - searched for {{ platform.install.installer_file }}. Preparing to copy the installer bin from the Tower server..."
  when: result.matched == 0

- name: Copy the bin file from the Tower server where the playbook is running if it doesn't exist on the target host
  # fetch:
  copy:
    src: "/tmp/ecp/{{ platform.install.installer_file }}"
    dest: "/tmp/{{ platform.install.installer_file }}"
    mode: a+x
    # NOTE: include the following options if SELinux is set to enforcing
    # seuser: "system_u"
    # serole: "object_r"
    # setype: "httpd_sys_content_t"
    # selevel: "s0"
  when: result.matched == 0

- name: Update the fact for the path with location of the copied installer file  
  set_fact:
    file_path: "/tmp/{{ platform.install.installer_file }}"
    cacheable: True
  when: result.matched == 0

- name: Report the command being run to uninstall ECP
  debug:
    msg: "Running the command: {{ file_path }} --erase --force"

- name: Run the installer with the --erase and --force option
  command: "{{ file_path }} --erase --force"

- name: Report the command being run to remove the ECP installer
  debug:
    msg: "Running the command: /bin/rm -f {{ file_path }}"

# Use /bin/rm in case rm is aliased to rm -i
- name: Remove the installer file
  command: "/bin/rm -f {{ file_path }}"

- name: Reboot the host
  reboot: 
    reboot_timeout: 600




