---
# This task uninstalls ECP components on the designated hosts by running the installer with the --erase option on each host and then removing the installer.
# It uses only one platform variable - platform.install.version as it mostly concerned with file manipulation and does not interact with ECP directly  
# NOTE: Prior to running this playbook, the installer bin file needs to be placed in the /tmp/ecp folder on the Tower server. 

- name: Find the location(s) of the installer bin file if it exists
  ansible.builtin.find:
    paths: /
    recurse: yes
    patterns: "*-cp-*-release-*.bin"
  register: result

- name: Report the path from the result of the find
  debug:
    msg: "There were {{ result.matched }} instances of the installer file found. The path to the first instance of the installer file is: {{ result.files[0].path }}"

- name: Report the result of the find
  debug:
    msg: "The file data is: {{ result.files[0] }}"

- name: Create a fact for the path of the installer file if one exists on the host 
  set_fact:
    file_path: "{{ result.files[0].path }}"
    cacheable: True
  when: result.matched >= 0 

- name: Create a fact for the path of the installer file if one doesn't exist 
  set_fact:
    file_path: "/opt/bluedata/bundles/{{ platform.install.version }}.bin"
    cacheable: True
  when: result.matched == 0 

- name: Set file stats for the installer file
  stat:
    path: "{{ file_path }}"
  register: file_data
  when: result.matched >= 0 

- name: Report if the bin file exists and is executable
  debug:
    msg: "The file {{ file_path }} exists and is executable. Preparing to uninstall ECP..."
  when: 
    - file_data.stat.exists
    - file_data.stat.executable  

- name: Report if the bin file exists and is NOT executable
  debug:
    msg: "The file {{ file_path }} exists but is NOT executable. Changing installer file to executable and preparing to uninstall ECP..."
  when: 
    - file_data.stat.exists
    - not file_data.stat.executable  

- name: Report if the bin file does NOT exist
  debug:
    msg: "The file {{ file_path }} does NOT exist. Preparing to copy the installer bin from the Tower server..."
  when: not file_data.stat.exists

- name: Copy the bin file from the Tower server if it doesn't exist on the target host
  fetch:
    src: "/tmp/ecp/{{ platform.install.version }}.bin"
    dest: "/tmp/{{ platform.install.verion }}.bin"
    remote_src: yes
    mode: a+x
    # NOTE: include the following options if SELinux is set to enforcing
    # seuser: "system_u"
    # serole: "object_r"
    # setype: "httpd_sys_content_t"
    # selevel: "s0"
  when: not file_data.stat.exists

- name: Make the installer bin executable if it exists and isn't executable
  file:
    path: "{{ file_path }}"
    mode: a+x
  when: 
    - file_data.stat.exists
    - not file_data.stat.executable

- name: Run the installer with the --erase option
  command: "{{ file_path }} --erase"



