apiVersion: v1
kind: PersistentVolume
metadata:
  name: gms-monitoring-local-pv-<hostname>
spec:
  capacity:
    storage: 1800Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: gms-monitoring-sc
  local:
    path: /dev/gmsmonitoring/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "<hostname>"
       