---
  - name: Add K8s hosts
    hosts: localhost
    gather_facts: false
    tasks:
    - name: Obtain session token
      uri:
        url: http://{{ primary_controller }}:8080/api/v1/login
        return_content: yes
        method: POST
        body_format: json
        body: { "name": "{{ credentials.site_admin_id }}", "password": "{{ credentials.site_admin_password }}" }
        status_code: 201
      register: session_res

    - name: Create a fact with the session info from the API call  
      set_fact:
        session_id: "{{ session_res.location  | urlsplit('path') }}"
        template_name: "templates/add_k8s_host.j2"
        cacheable: True  
  
    # Get the current list of Host tages 
    - name: Get the current set of host tags 
      uri:
        url: http://{{ primary_controller }}:8080/api/v2/tag
        return_content: yes
        headers:
          X-BDS-SESSION: "{{ session_id }}" 
          accept: "application/json"
        method: GET
        status_code: 200
      register: host_tags_res
   
    - name: Create a fact with parsed list of host tags from the API call  
      set_fact:
        # host_tags: "{{ host_tags_res.json | json_query('_embedded.tags[*].{tag_id: _links.self.href, name: label.name, description: label.description}')  }}"
        host_tags: "{{ host_tags_res.json }}"
        cacheable: True  

    - debug:
        msg: "Tag Id: {{ host_tags | json_query('_embedded.tags[?label.name==`dc_tag`]._links.self.href') | replace('[', '') | replace('u', '') }}"
    
#    - name: Add hosts to the current set of k8s hosts
#      include_tasks: add_k8s_host_block.yml   
#      loop: "{{ new_k8s_hosts }}"

    - name: Log out of session
      uri:
        url: "{{ session_res.location }}"
        return_content: yes
        headers:
          X-BDS-SESSION: "{{ session_id }}" 
        method: DELETE
        status_code: 204
      register: delsession_res

 #   - debug:
 #       msg: "Session: {{ session_res.location  | urlsplit('path') }} -- K8s hosts result: {{ res.stdout }}"
        
        
          
