---
  - name: Create K8s cluster
    hosts: localhost
    gather_facts: true
    roles:
      - role: platform
        vars:
          ecp_session: "{{ hostvars[inventory_hostname].ecp_session }}" 
          k8s_hosts: "{{ hostvars[inventory_hostname].k8s_hosts }}"
          create_k8s_cluster: yes
          
          
          
