---
  - name: Create K8s cluster
    hosts: localhost
    gather_facts: true
    become: yes
    roles:
      - role: platform
        vars:
          create_k8s_cluster: yes
          
          
          
