---
  - name: Install platform
    hosts: localhost
    gather_facts: false
    roles:
      - role: platform
        vars:
          install: yes
          configure_ha: yes
          configure_airgap: yes
          add_k8s_hosts: yes
          create_k8s_cluster: yes
          create_k8s_tenant: yes
          install_istio: yes
          install_openebs: yes
          add_k8s_hosts_to_cluster: yes
          
          
