---
  - name: Install ECP control plane
    hosts: localhost
    gather_facts: false
    roles:
      - role: platform
        vars:
          # For RTLAB the ansible user is awx
          ansible_user: awx
          # ansible_user: stack
          install_controller: yes
          add_gateways: yes
          add_ha_workers: yes
          configure_ha: yes
          add_host_tags: yes

          # To run the task to configure a custom ECP gateway port range, set configure_gateway_ports to yes
          configure_gateway_ports: no
          # To run the task to configure ECP for an airgap installation, set configure_airgap to yes
          configure_airgap: no
          #To run the task to configure ECP notifications, set configure_notficiation to yes
          configure_notification: no

          # NOTE: These tasks are only needed for ECP 5.1
          apply_ecp_patches: no
          apply_ntp_fix_primary: no
          apply_ntp_fix_shadow: no
          
          
