---
  - name: Remove K8s nodes from cluster
    hosts: localhost
    gather_facts: false
    roles:
      - role: platform
        vars:
          remove_nodes_from_k8s_cluster: yes
          
   
    
