---
  - hosts: controllers, gateways, k8s_hosts, epic_hosts
    gather_facts: false
#    become: yes
#    become_user: stack
#    become_user: "{{ credentials.ssh.username }}"
    roles:
      - role: platform
        vars:
          run_prechecks: yes
